### ISSUE TITLE
Planet Data owl

### ISSUE THREAD

**Issue by GAECLab** [GAECLab/NR491_Fall2022#7]
Hi @mdgaines for the Week6 Planet API exercise - did you dwl the data for L Raleigh with Vini's Planet API notebook? I tried it and it downloads one image instead of 18 as there are in the folder for this exercise.
I changed the last plotting for this nb and added a HW, pls have a look, now the branch is merged into main.
Do we still need exercise1 to exercise4 branches? if not, let's please remove them, thank you

**Comment by mdgaines** [comment]
Vini downloaded the data and then I used the udm2 to remove a few images. @vperin how did you download the Lake Raleigh PS images that you shared with me?
I will look at the nb and remove those other branches.

**Comment by vperin** [comment]
@MirelaGTulbure it only downloaded 1 image because of the dates that I left on the notebook. I left it there on purpose. So that If students are running the code during the class it does not take too long, avoiding them going over their quota etc.  

@mdgaines you can use the notebook on week5 "Planet_API" to download the images. Just set the correct dates, I used the dates that you shared with me a while a ago to get those 18 images.

**Comment by GAECLab** [comment]
cool that you both, will close this
